package com.teamarc.planit.entity.enums;

public enum NotificationType {
    BOOKING_CONFIRMATION, BOOKING_CANCELLED, PAYMENT_SUCCESS, 
    REFUND_INITIATED, REVIEW_REQUEST, MESSAGE_RECEIVED, 
    EVENT_REMINDER, DISPUTE_OPENED, TASK_ASSIGNED, VENDOR_UPDATE
}
