spring.application.name=demo

jwt.secretKey=uzrehgihEFJOHNFEUGHRGHER8TNQ4IJNVJFBJUGH5IT6J358Y5YNETAKJHHT9IHAJTEJYerha9urhtkjdfbngouetojethy697hj5hnijfgnbnkmzgiuo

spring.datasource.url=jdbc:postgresql://ep-damp-thunder-atez1g76-pooler.c-9.us-east-1.aws.neon.tech/neondb?user=neondb_owner&password=npg_7UGHIQ1hXVDA&sslmode=require&channelBinding=require
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect