spring.application.name=demo

jwt.secretKey=uzrehgihEFJOHNFEUGHRGHER8TNQ4IJNVJFBJUGH5IT6J358Y5YNETAKJHHT9IHAJTEJYerha9urhtkjdfbngouetojethy697hj5hnijfgnbnkmzgiuo

spring.datasource.url=${JDBC_URL}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect